export const ALL_ACHIEVEMENTS = [
  // Focus & Productivity (20)
  { id: 'ach_1', title: 'Deep Work Pioneer', description: 'Complete 10 hours of uninterrupted focus', target: 10, reward: 100, duration: 7, type: 'focus' },
  { id: 'ach_2', title: 'Pomodoro Master', description: 'Complete 50 pomodoro sessions', target: 50, reward: 250, duration: 30, type: 'quantity' },
  { id: 'ach_3', title: 'Flow State', description: 'Focus for 4 hours in a single day', target: 4, reward: 150, duration: 1, type: 'focus' },
  { id: 'ach_4', title: 'Week of Focus', description: 'Log focus time every day for a week', target: 7, reward: 200, duration: 7, type: 'streak' },
  { id: 'ach_5', title: 'Focus Marathon', description: 'Complete 100 hours of focus', target: 100, reward: 1000, duration: 30, type: 'focus' },
  { id: 'ach_6', title: 'Task Crusher', description: 'Complete 20 tasks in a day', target: 20, reward: 100, duration: 1, type: 'quantity' },
  { id: 'ach_7', title: 'Zero Distractions', description: 'Zero aborted sessions for a week', target: 7, reward: 150, duration: 7, type: 'streak' },
  { id: 'ach_8', title: 'Early Riser Focus', description: 'Log 1 hour of focus before 8 AM', target: 1, reward: 50, duration: 1, type: 'focus' },
  { id: 'ach_9', title: 'Night Owl Focus', description: 'Log 2 hours of focus after 10 PM', target: 2, reward: 80, duration: 1, type: 'focus' },
  { id: 'ach_10', title: 'Consistent Worker', description: '30 days of logging at least 1 focus session', target: 30, reward: 500, duration: 30, type: 'streak' },
  { id: 'ach_11', title: 'Hyperfocus', description: 'Complete a single 3-hour focus session', target: 3, reward: 200, duration: 1, type: 'focus' },
  { id: 'ach_12', title: 'Weekend Hustle', description: 'Focus for 5 hours over the weekend', target: 5, reward: 150, duration: 2, type: 'focus' },
  { id: 'ach_13', title: 'Project Finisher', description: 'Accumulate 50 hours on a single tag', target: 50, reward: 400, duration: 30, type: 'focus' },
  { id: 'ach_14', title: '100 Day Challenge', description: 'Track focus for 100 consecutive days', target: 100, reward: 2000, duration: 100, type: 'streak' },
  { id: 'ach_15', title: 'Time Lord', description: '1000 hours of total focus time logged', target: 1000, reward: 10000, duration: 365, type: 'focus' },
  { id: 'ach_16', title: 'Productivity Guru', description: 'Complete 500 focus sessions', target: 500, reward: 5000, duration: 365, type: 'quantity' },
  { id: 'ach_17', title: 'Daily Drive', description: 'Focus for 2 hours every day for a month', target: 30, reward: 800, duration: 30, type: 'streak' },
  { id: 'ach_18', title: 'Morning Mastery', description: 'Focus for 3 hours before 12 PM', target: 3, reward: 120, duration: 1, type: 'focus' },
  { id: 'ach_19', title: 'Evening Execution', description: 'Focus for 3 hours after 6 PM', target: 3, reward: 120, duration: 1, type: 'focus' },
  { id: 'ach_20', title: 'Relentless', description: 'Complete 10 pomodoro sessions in one day', target: 10, reward: 300, duration: 1, type: 'quantity' },

  // Habits & Consistency (20)
  { id: 'ach_21', title: 'Habit Starter', description: 'Complete all habits for 3 days', target: 3, reward: 50, duration: 3, type: 'streak' },
  { id: 'ach_22', title: 'Perfect Week', description: 'Complete all habits for 7 days', target: 7, reward: 150, duration: 7, type: 'streak' },
  { id: 'ach_23', title: 'Perfect Month', description: 'Complete all habits for 30 days', target: 30, reward: 600, duration: 30, type: 'streak' },
  { id: 'ach_24', title: 'Habit Builder', description: 'Create 5 new habits', target: 5, reward: 50, duration: 30, type: 'quantity' },
  { id: 'ach_25', title: '100 Completions', description: 'Complete any habit 100 times', target: 100, reward: 200, duration: 60, type: 'quantity' },
  { id: 'ach_26', title: 'Half Year Hero', description: '180 days streak on a single habit', target: 180, reward: 1000, duration: 180, type: 'streak' },
  { id: 'ach_27', title: 'Year Long Journey', description: '365 days streak on a single habit', target: 365, reward: 2500, duration: 365, type: 'streak' },
  { id: 'ach_28', title: 'Diversified', description: 'Maintain streaks on 5 different habits', target: 5, reward: 300, duration: 30, type: 'quantity' },
  { id: 'ach_29', title: 'Never Miss a Monday', description: 'Complete all habits for 4 consecutive Mondays', target: 4, reward: 150, duration: 28, type: 'streak' },
  { id: 'ach_30', title: 'Weekend Warrior', description: 'Complete all habits for 4 consecutive weekends', target: 8, reward: 200, duration: 28, type: 'streak' },
  { id: 'ach_31', title: '10K Check-ins', description: 'Complete 10,000 total habit entries', target: 10000, reward: 10000, duration: 365, type: 'quantity' },
  { id: 'ach_32', title: 'Flawless Routine', description: '100% completion rate for a week', target: 7, reward: 200, duration: 7, type: 'streak' },
  { id: 'ach_33', title: 'Recovery Master', description: 'Restore a streak after breaking it', target: 1, reward: 100, duration: 7, type: 'completion' },
  { id: 'ach_34', title: 'Morning Routine', description: 'Complete 3 habits before 9 AM', target: 3, reward: 100, duration: 1, type: 'completion' },
  { id: 'ach_35', title: 'Evening Wind-down', description: 'Complete 3 habits after 8 PM', target: 3, reward: 100, duration: 1, type: 'completion' },
  { id: 'ach_36', title: 'Habit Tycoon', description: 'Complete 500 habits', target: 500, reward: 2000, duration: 365, type: 'quantity' },
  { id: 'ach_37', title: 'Unbreakable', description: 'Never break a streak for 60 days', target: 60, reward: 1000, duration: 60, type: 'streak' },
  { id: 'ach_38', title: 'Routine Master', description: 'Keep a 90% completion rate for 30 days', target: 30, reward: 500, duration: 30, type: 'streak' },
  { id: 'ach_39', title: 'Habit Guru', description: 'Achieve a 100 day streak on 3 habits', target: 3, reward: 1500, duration: 100, type: 'quantity' },
  { id: 'ach_40', title: 'Daily Dozen', description: 'Complete 12 habits in a single day', target: 12, reward: 120, duration: 1, type: 'quantity' },

  // Lifestyle & Wellness (10)
  { id: 'ach_41', title: 'Hydration Hero', description: 'Track water intake for 30 days', target: 30, reward: 300, duration: 30, type: 'streak' },
  { id: 'ach_42', title: 'Bookworm', description: 'Read for 30 days consecutively', target: 30, reward: 350, duration: 30, type: 'streak' },
  { id: 'ach_43', title: 'Mindful Master', description: 'Meditate for 10 hours total', target: 10, reward: 400, duration: 30, type: 'focus' },
  { id: 'ach_44', title: 'Fitness Junkie', description: 'Exercise 20 times in a month', target: 20, reward: 400, duration: 30, type: 'quantity' },
  { id: 'ach_45', title: 'Digital Detox', description: 'No screen time habits tracked for a weekend', target: 2, reward: 150, duration: 2, type: 'streak' },
  { id: 'ach_46', title: 'Sleep Optimizer', description: '8 hours of sleep tracked for a week', target: 7, reward: 200, duration: 7, type: 'streak' },
  { id: 'ach_47', title: 'Journaler', description: 'Write 50 journal entries', target: 50, reward: 300, duration: 60, type: 'quantity' },
  { id: 'ach_48', title: 'Language Learner', description: 'Study a language for 14 consecutive days', target: 14, reward: 250, duration: 14, type: 'streak' },
  { id: 'ach_49', title: 'Creative Soul', description: 'Log 20 hours of creative work', target: 20, reward: 350, duration: 30, type: 'focus' },
  { id: 'ach_50', title: 'Grateful Heart', description: 'Log gratitude for 30 days', target: 30, reward: 300, duration: 30, type: 'streak' },
  
  // Challenges & Community (10)
  { id: 'ach_51', title: 'First Challenge', description: 'Join your first achievement', target: 1, reward: 50, duration: 1, type: 'completion' },
  { id: 'ach_52', title: 'Challenge Accepted', description: 'Join 5 achievements', target: 5, reward: 150, duration: 30, type: 'quantity' },
  { id: 'ach_53', title: 'Overachiever', description: 'Complete 10 achievements', target: 10, reward: 500, duration: 90, type: 'completion' },
  { id: 'ach_54', title: 'Top 1%', description: 'Earn 10,000 total XP', target: 10000, reward: 1000, duration: 365, type: 'quantity' },
  { id: 'ach_55', title: 'Ultimate Champion', description: 'Complete 50 other achievements', target: 50, reward: 10000, duration: 365, type: 'completion' },
  { id: 'ach_56', title: 'Weekend Zen', description: 'Meditate for 1 hour on Saturday and Sunday', target: 2, reward: 100, duration: 2, type: 'focus' },
  { id: 'ach_57', title: 'Night Reader', description: 'Read a book after 9 PM for 5 days', target: 5, reward: 120, duration: 7, type: 'streak' },
  { id: 'ach_58', title: 'Collector', description: 'Unlock 20 Badges', target: 20, reward: 500, duration: 180, type: 'quantity' },
  { id: 'ach_59', title: 'App Enthusiast', description: 'Open the app 100 days in a row', target: 100, reward: 1500, duration: 100, type: 'streak' },
  { id: 'ach_60', title: 'Trendsetter', description: 'Maintain streaks on all active habits for a week', target: 7, reward: 300, duration: 7, type: 'streak' }
];

export const ALL_BADGES = [
  // Getting Started (10)
  { id: 'first_habit', name: 'First Habit', icon: 'leaf', color: '#22c55e', description: 'Create your first habit', category: 'Getting Started' },
  { id: 'first_completion', name: 'First Step', icon: 'footsteps', color: '#3b82f6', description: 'Complete your first habit entry', category: 'Getting Started' },
  { id: 'profile_setup', name: 'Identity', icon: 'person', color: '#8b5cf6', description: 'Set up your profile', category: 'Getting Started' },
  { id: 'first_week', name: 'First Week', icon: 'calendar', color: '#ec4899', description: 'Use the app for 7 days', category: 'Getting Started' },
  { id: 'explorer', name: 'Explorer', icon: 'compass', color: '#06b6d4', description: 'Explore all features', category: 'Getting Started' },
  { id: 'first_focus', name: 'Focus Novice', icon: 'time', color: '#10b981', description: 'Complete your first focus session', category: 'Getting Started' },
  { id: 'first_achievement', name: 'Go Getter', icon: 'star', color: '#eab308', description: 'Join your first achievement', category: 'Getting Started' },
  { id: 'first_insight', name: 'Data Curious', icon: 'pie-chart', color: '#6366f1', description: 'View your insights tab', category: 'Getting Started' },
  { id: 'first_settings', name: 'Tinkerer', icon: 'settings', color: '#94a3b8', description: 'Change a setting', category: 'Getting Started' },
  { id: 'first_share', name: 'Social', icon: 'share-social', color: '#f43f5e', description: 'Share a milestone', category: 'Getting Started' },
  
  // Streaks (25)
  { id: '3_day_streak', name: '3 Day Streak', icon: 'flame', color: '#f97316', description: 'Maintain a 3-day streak', category: 'Streaks' },
  { id: 'week_warrior', name: 'Week Warrior', icon: 'flame', color: '#ef4444', description: 'Maintain a 7-day streak', category: 'Streaks' },
  { id: '10_day_streak', name: 'Double Digits', icon: 'flame', color: '#ea580c', description: 'Maintain a 10-day streak', category: 'Streaks' },
  { id: 'two_week_titan', name: 'Two Week Titan', icon: 'flame', color: '#dc2626', description: 'Maintain a 14-day streak', category: 'Streaks' },
  { id: '21_day_streak', name: 'Habit Former', icon: 'flame', color: '#b91c1c', description: 'Maintain a 21-day streak', category: 'Streaks' },
  { id: 'monthly_master', name: 'Monthly Master', icon: 'flame', color: '#b91c1c', description: 'Maintain a 30-day streak', category: 'Streaks' },
  { id: '40_day_streak', name: 'Quarantine', icon: 'flame', color: '#991b1b', description: 'Maintain a 40-day streak', category: 'Streaks' },
  { id: 'streak_50', name: 'Unstoppable', icon: 'flame', color: '#991b1b', description: 'Maintain a 50-day streak', category: 'Streaks' },
  { id: '60_day_streak', name: 'Two Months', icon: 'flame', color: '#991b1b', description: 'Maintain a 60-day streak', category: 'Streaks' },
  { id: '75_day_streak', name: 'Diamond Will', icon: 'flame', color: '#7f1d1d', description: 'Maintain a 75-day streak', category: 'Streaks' },
  { id: '90_day_streak', name: 'Quarter', icon: 'flame', color: '#7f1d1d', description: 'Maintain a 90-day streak', category: 'Streaks' },
  { id: 'streak_100', name: 'Centurion', icon: 'flame', color: '#7f1d1d', description: 'Maintain a 100-day streak', category: 'Streaks' },
  { id: 'streak_120', name: 'Trimester', icon: 'flame', color: '#ea580c', description: 'Maintain a 120-day streak', category: 'Streaks' },
  { id: 'streak_150', name: 'Halfway There', icon: 'flame', color: '#ea580c', description: 'Maintain a 150-day streak', category: 'Streaks' },
  { id: 'streak_180', name: 'Half Year Hero', icon: 'flame', color: '#ea580c', description: 'Maintain a 180-day streak', category: 'Streaks' },
  { id: 'streak_200', name: 'Double Centurion', icon: 'flame', color: '#c2410c', description: 'Maintain a 200-day streak', category: 'Streaks' },
  { id: 'streak_250', name: 'Relentless', icon: 'flame', color: '#c2410c', description: 'Maintain a 250-day streak', category: 'Streaks' },
  { id: 'streak_300', name: 'Spartan', icon: 'flame', color: '#c2410c', description: 'Maintain a 300-day streak', category: 'Streaks' },
  { id: 'streak_365', name: 'A Year of Focus', icon: 'flame', color: '#c2410c', description: 'Maintain a 365-day streak', category: 'Streaks' },
  { id: 'streak_400', name: 'Beyond Limits', icon: 'flame', color: '#9a3412', description: 'Maintain a 400-day streak', category: 'Streaks' },
  { id: 'streak_500', name: 'Legendary', icon: 'flame', color: '#9a3412', description: 'Maintain a 500-day streak', category: 'Streaks' },
  { id: 'streak_600', name: 'Unbroken', icon: 'flame', color: '#7c2d12', description: 'Maintain a 600-day streak', category: 'Streaks' },
  { id: 'streak_730', name: 'Two Years', icon: 'flame', color: '#7c2d12', description: 'Maintain a 730-day streak', category: 'Streaks' },
  { id: 'streak_800', name: 'Godlike', icon: 'flame', color: '#7c2d12', description: 'Maintain a 800-day streak', category: 'Streaks' },
  { id: 'streak_1000', name: 'Immortal', icon: 'flame', color: '#451a03', description: 'Maintain a 1000-day streak', category: 'Streaks' },
  
  // Milestones (25)
  { id: '10_completions', name: '10 Completions', icon: 'checkmark-circle', color: '#22c55e', description: 'Complete 10 habit entries', category: 'Milestones' },
  { id: '25_completions', name: '25 Completions', icon: 'checkmark-circle', color: '#22c55e', description: 'Complete 25 habit entries', category: 'Milestones' },
  { id: '50_completions', name: 'Half Century', icon: 'checkmark-done', color: '#16a34a', description: 'Complete 50 habit entries', category: 'Milestones' },
  { id: '75_completions', name: '75 Completions', icon: 'checkmark-done', color: '#16a34a', description: 'Complete 75 habit entries', category: 'Milestones' },
  { id: 'century_club', name: 'Century Club', icon: 'ribbon', color: '#15803d', description: 'Complete 100 habit entries', category: 'Milestones' },
  { id: '150_completions', name: '150 Completions', icon: 'ribbon', color: '#15803d', description: 'Complete 150 habit entries', category: 'Milestones' },
  { id: '200_completions', name: 'Double Century', icon: 'ribbon', color: '#166534', description: 'Complete 200 habit entries', category: 'Milestones' },
  { id: '250_completions', name: 'Quarter K', icon: 'medal', color: '#166534', description: 'Complete 250 habit entries', category: 'Milestones' },
  { id: '300_completions', name: '300 Completions', icon: 'medal', color: '#166534', description: 'Complete 300 habit entries', category: 'Milestones' },
  { id: '400_completions', name: '400 Completions', icon: 'medal', color: '#14532d', description: 'Complete 400 habit entries', category: 'Milestones' },
  { id: '500_completions', name: 'High Achiever', icon: 'trophy', color: '#14532d', description: 'Complete 500 habit entries', category: 'Milestones' },
  { id: '750_completions', name: '750 Completions', icon: 'trophy', color: '#065f46', description: 'Complete 750 habit entries', category: 'Milestones' },
  { id: '1000_completions', name: 'Grandmaster', icon: 'star', color: '#065f46', description: 'Complete 1000 habit entries', category: 'Milestones' },
  { id: '1500_completions', name: '1500 Completions', icon: 'star', color: '#064e3b', description: 'Complete 1500 habit entries', category: 'Milestones' },
  { id: '2000_completions', name: '2000 Completions', icon: 'shield-checkmark', color: '#064e3b', description: 'Complete 2000 habit entries', category: 'Milestones' },
  { id: '2500_completions', name: 'Titan', icon: 'shield-checkmark', color: '#064e3b', description: 'Complete 2500 habit entries', category: 'Milestones' },
  { id: '3000_completions', name: '3000 Completions', icon: 'planet', color: '#022c22', description: 'Complete 3000 habit entries', category: 'Milestones' },
  { id: '4000_completions', name: '4000 Completions', icon: 'planet', color: '#022c22', description: 'Complete 4000 habit entries', category: 'Milestones' },
  { id: '5000_completions', name: 'Demi-God', icon: 'planet', color: '#022c22', description: 'Complete 5000 habit entries', category: 'Milestones' },
  { id: '6000_completions', name: '6000 Completions', icon: 'infinite', color: '#0f172a', description: 'Complete 6000 habit entries', category: 'Milestones' },
  { id: '7500_completions', name: '7500 Completions', icon: 'infinite', color: '#0f172a', description: 'Complete 7500 habit entries', category: 'Milestones' },
  { id: '8000_completions', name: '8000 Completions', icon: 'infinite', color: '#0f172a', description: 'Complete 8000 habit entries', category: 'Milestones' },
  { id: '9000_completions', name: '9000 Completions', icon: 'infinite', color: '#0f172a', description: 'Complete 9000 habit entries', category: 'Milestones' },
  { id: '10000_completions', name: 'Zenith', icon: 'infinite', color: '#0f172a', description: 'Complete 10000 habit entries', category: 'Milestones' },
  { id: '15000_completions', name: 'Ascended', icon: 'infinite', color: '#000000', description: 'Complete 15000 habit entries', category: 'Milestones' },

  // Focus (25)
  { id: 'focus_hour', name: 'Hour of Power', icon: 'hourglass', color: '#2563eb', description: 'Accumulate 60 minutes of focus time', category: 'Focus' },
  { id: 'focus_5h', name: 'Deep Diver', icon: 'stopwatch', color: '#1d4ed8', description: 'Accumulate 5 hours of focus time', category: 'Focus' },
  { id: 'focus_10h', name: 'Focus Marathon', icon: 'stopwatch', color: '#1d4ed8', description: 'Accumulate 10 hours of focus time', category: 'Focus' },
  { id: 'focus_25h', name: 'Committed', icon: 'timer', color: '#1e40af', description: 'Accumulate 25 hours of focus time', category: 'Focus' },
  { id: 'focus_50h', name: 'Deep Worker', icon: 'timer', color: '#1e40af', description: 'Accumulate 50 hours of focus time', category: 'Focus' },
  { id: 'focus_75h', name: 'Zone Master', icon: 'eye', color: '#1e3a8a', description: 'Accumulate 75 hours of focus time', category: 'Focus' },
  { id: 'focus_100h', name: 'Focus Master', icon: 'eye', color: '#1e3a8a', description: 'Accumulate 100 hours of focus time', category: 'Focus' },
  { id: 'focus_150h', name: 'Unwavering', icon: 'water', color: '#172554', description: 'Accumulate 150 hours of focus time', category: 'Focus' },
  { id: 'focus_200h', name: 'Monk Mode', icon: 'water', color: '#172554', description: 'Accumulate 200 hours of focus time', category: 'Focus' },
  { id: 'focus_250h', name: 'Flow State', icon: 'water', color: '#172554', description: 'Accumulate 250 hours of focus time', category: 'Focus' },
  { id: 'focus_300h', name: 'Absorbed', icon: 'flash', color: '#8b5cf6', description: 'Accumulate 300 hours of focus time', category: 'Focus' },
  { id: 'focus_400h', name: 'Transcendence', icon: 'flash', color: '#8b5cf6', description: 'Accumulate 400 hours of focus time', category: 'Focus' },
  { id: 'focus_500h', name: 'Laser Beam', icon: 'flash', color: '#8b5cf6', description: 'Accumulate 500 hours of focus time', category: 'Focus' },
  { id: 'focus_600h', name: 'Pinnacle', icon: 'flash', color: '#8b5cf6', description: 'Accumulate 600 hours of focus time', category: 'Focus' },
  { id: 'focus_750h', name: 'Singularity', icon: 'infinite', color: '#7c3aed', description: 'Accumulate 750 hours of focus time', category: 'Focus' },
  { id: 'focus_1000h', name: 'Time Lord', icon: 'infinite', color: '#7c3aed', description: 'Accumulate 1000 hours of focus time', category: 'Focus' },
  { id: 'focus_1500h', name: 'Time Wizard', icon: 'infinite', color: '#5b21b6', description: 'Accumulate 1500 hours of focus time', category: 'Focus' },
  { id: 'focus_2000h', name: 'Master of Time', icon: 'infinite', color: '#4c1d95', description: 'Accumulate 2000 hours of focus time', category: 'Focus' },
  { id: 'pomodoro_10', name: 'Pomodoro Initiate', icon: 'pizza', color: '#ef4444', description: 'Complete 10 Pomodoro sessions', category: 'Focus' },
  { id: 'pomodoro_50', name: 'Pomodoro Pro', icon: 'pizza', color: '#ef4444', description: 'Complete 50 Pomodoro sessions', category: 'Focus' },
  { id: 'pomodoro_100', name: 'Pomodoro King', icon: 'pizza', color: '#ef4444', description: 'Complete 100 Pomodoro sessions', category: 'Focus' },
  { id: 'pomodoro_250', name: 'Pomodoro Master', icon: 'pizza', color: '#b91c1c', description: 'Complete 250 Pomodoro sessions', category: 'Focus' },
  { id: 'pomodoro_500', name: 'Tomato Farmer', icon: 'pizza', color: '#b91c1c', description: 'Complete 500 Pomodoro sessions', category: 'Focus' },
  { id: 'pomodoro_1000', name: 'Sauce Boss', icon: 'pizza', color: '#991b1b', description: 'Complete 1000 Pomodoro sessions', category: 'Focus' },
  { id: 'distraction_free', name: 'Iron Will', icon: 'shield', color: '#64748b', description: 'Zero interrupted focus sessions for a month', category: 'Focus' },

  // Special & Hidden (35)
  { id: 'early_bird', name: 'Early Bird', icon: 'partly-sunny', color: '#fbbf24', description: 'Complete a habit before 6 AM', category: 'Special' },
  { id: 'night_owl', name: 'Night Owl', icon: 'moon', color: '#6366f1', description: 'Complete a habit after 10 PM', category: 'Special' },
  { id: 'weekend_warrior_lifestyle', name: 'Weekend Warrior', icon: 'bicycle', color: '#10b981', description: 'Complete all habits on weekends', category: 'Special' },
  { id: 'perfect_week', name: 'Perfect Week', icon: 'star', color: '#eab308', description: 'Complete all habits for 7 days', category: 'Special' },
  { id: 'perfect_month', name: 'Perfect Month', icon: 'calendar', color: '#a855f7', description: 'Complete all habits for 30 days', category: 'Special' },
  { id: 'perfect_quarter', name: 'Perfect Quarter', icon: 'calendar', color: '#d946ef', description: 'Complete all habits for 90 days', category: 'Special' },
  { id: 'perfect_year', name: 'Perfect Year', icon: 'calendar', color: '#ec4899', description: 'Complete all habits for 365 days', category: 'Special' },
  { id: 'comeback_kid', name: 'Comeback Kid', icon: 'refresh', color: '#a855f7', description: 'Resume tracking after a 7-day break', category: 'Special' },
  { id: 'phoenix', name: 'Phoenix', icon: 'flame', color: '#f43f5e', description: 'Resume tracking after a 30-day break', category: 'Special' },
  { id: 'overachiever', name: 'Overachiever', icon: 'rocket', color: '#ec4899', description: 'Complete 10+ habits in one day', category: 'Special' },
  { id: 'steady_pace', name: 'Steady Pace', icon: 'walk', color: '#14b8a6', description: 'Track habits for 100 consecutive days', category: 'Special' },
  { id: 'multi_tasker', name: 'Multi-Tasker', icon: 'layers', color: '#f43f5e', description: 'Have 20 active habits at once', category: 'Special' },
  { id: 'spring_cleaner', name: 'Spring Cleaner', icon: 'trash', color: '#64748b', description: 'Archive 5 old habits', category: 'Special' },
  { id: 'reflective', name: 'Reflective', icon: 'book', color: '#d946ef', description: 'Write 50 journal entries', category: 'Special' },
  { id: 'social_butterfly', name: 'Social Butterfly', icon: 'people', color: '#0ea5e9', description: 'Join 5 achievements', category: 'Special' },
  { id: 'champion', name: 'Champion', icon: 'trophy', color: '#fb923c', description: 'Win an achievement challenge', category: 'Special' },
  { id: 'trendsetter', name: 'Trendsetter', icon: 'trending-up', color: '#84cc16', description: 'Improve completion rate by 20% in a month', category: 'Special' },
  { id: 'all_habits_completed', name: 'Flawless Day', icon: 'sunny', color: '#eab308', description: 'Complete all daily habits', category: 'Special' },
  { id: 'focus_flow_master', name: 'FocusFlow Master', icon: 'diamond', color: '#06b6d4', description: 'Unlock 40 other badges', category: 'Special' },
  { id: 'beta_tester', name: 'Beta Tester', icon: 'bug', color: '#8b5cf6', description: 'Joined during the beta period', category: 'Special' },
  { id: 'collector', name: 'Collector', icon: 'albums', color: '#f59e0b', description: 'Unlock 25 badges', category: 'Special' },
  { id: 'hoarder', name: 'Hoarder', icon: 'archive', color: '#d97706', description: 'Unlock 50 badges', category: 'Special' },
  { id: 'completionist', name: 'Completionist', icon: 'medal', color: '#b45309', description: 'Unlock 75 badges', category: 'Special' },
  { id: 'perfectionist', name: 'Perfectionist', icon: 'trophy', color: '#78350f', description: 'Unlock 90 badges', category: 'Special' },
  { id: 'ultimatist', name: 'Ultimatist', icon: 'diamond', color: '#000000', description: 'Unlock all 100 badges', category: 'Special' },
  { id: 'five_am_club', name: '5 AM Club', icon: 'alarm', color: '#14b8a6', description: 'Complete a habit before 5 AM', category: 'Special' },
  { id: 'midnight_oil', name: 'Midnight Oil', icon: 'bonfire', color: '#f43f5e', description: 'Complete a focus session after midnight', category: 'Special' },
  { id: 'habit_stacker', name: 'Habit Stacker', icon: 'layers', color: '#3b82f6', description: 'Complete 5 habits within 1 hour', category: 'Special' },
  { id: 'laser_focus', name: 'Laser Focus', icon: 'flash', color: '#eab308', description: 'Focus for 2 hours with no breaks', category: 'Special' },
  { id: 'marathon_runner', name: 'Marathon Runner', icon: 'walk', color: '#22c55e', description: 'Focus for 4 hours with no breaks', category: 'Special' },
  { id: 'iron_mind', name: 'Iron Mind', icon: 'barbell', color: '#64748b', description: 'Focus for 6 hours with no breaks', category: 'Special' },
  { id: 'unstoppable_force', name: 'Unstoppable', icon: 'rocket', color: '#ef4444', description: 'Focus for 8 hours with no breaks', category: 'Special' },
  { id: 'zen_master', name: 'Zen Master', icon: 'leaf', color: '#10b981', description: 'Log 50 hours of meditation/mindfulness', category: 'Special' },
  { id: 'book_worm', name: 'Book Worm', icon: 'book', color: '#8b5cf6', description: 'Log 50 hours of reading', category: 'Special' },
  { id: 'polymath', name: 'Polymath', icon: 'school', color: '#8b5cf6', description: 'Log 100 hours of learning', category: 'Special' }
];
